# numpy array 練習

* %pylab inline，直接import numpy和matplotlib，不用再打縮寫np和plt

In [83]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


### 型態，數字後面有點沒點差很多

In [84]:
a = 8
print a, type(a)

8 <type 'int'>


In [85]:
a = 8.
print a, type(a)

8.0 <type 'float'>


### 產生1d array
* 用for
* 用rand/randn
* 用linsapce，要描點畫圖的時候，很常用到
* ones/zeros/eye/full

In [86]:
a = array([i for i in range(10)])
print a

[0 1 2 3 4 5 6 7 8 9]


In [87]:
# rand = a uniform distribution over [0, 1).
a = array(rand(10))
print a

[ 0.76301615  0.46514153  0.02133523  0.04122167  0.76319405  0.11989162
  0.95099657  0.79807341  0.03740514  0.38568139]


In [88]:
# randn = a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 
a = array(randn(10))
print a

[ 1.00131573  0.12549132  1.30130295 -0.35678309 -0.04723123 -0.27931699
  1.33351588  1.17353804 -0.46826019  1.22552105]


In [89]:
a = linspace(-1, 1, 10)
print a

[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [90]:
a = ones(10)
print a

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [91]:
a = zeros(10)
print a

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [92]:
a = eye(3)
print a

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [93]:
a = full(10, 8.)
print a

[ 8.  8.  8.  8.  8.  8.  8.  8.  8.  8.]


### array 選資料 (indexing and slicing)

In [94]:
a = array([i for i in range(10)])
print a

[0 1 2 3 4 5 6 7 8 9]


In [95]:
print a[0]

0


In [96]:
# 抓1~3，實際上是回傳[1 2]
print a[1:3]

[1 2]


In [97]:
# 從最後開始
print a[-1]

9


In [98]:
#從第5個開始一直到最後
print a[5:]

[5 6 7 8 9]


In [99]:
#從第0個開始一直到5
print a[:5]

[0 1 2 3 4]


### array操作，很重要的技巧

* 1d -> 2d (蔡炎龍:很重要，有時候在1d array比較容易處理問題，處理完再轉回去2d)
* append data (儲存每次新的結果err,result...)
* 1d/2d 水平疊資料

In [100]:
a = array(rand(10))
a.shape

(10L,)

In [101]:
# 改成2d array
a.shape = (5, 2)
print a

[[ 0.41310388  0.52553425]
 [ 0.7810508   0.95052939]
 [ 0.34457488  0.49289148]
 [ 0.67120055  0.34663667]
 [ 0.86390081  0.07143803]]


In [102]:
# 再變回來 1d array
a.shape = (10)
print a

[ 0.41310388  0.52553425  0.7810508   0.95052939  0.34457488  0.49289148
  0.67120055  0.34663667  0.86390081  0.07143803]


In [103]:
# append data
a = array([11, 22, 33])
a = append(a, [77, 88, 99])
print a

[11 22 33 77 88 99]


In [104]:
# 1d 水平疊資料
a = array([11, 22, 33])
b = array([11, 22, 33, 44])
L = list()
L.append(a)
L.append(b)
print L
print L[0]

[array([11, 22, 33]), array([11, 22, 33, 44])]
[11 22 33]


In [105]:
a = array([[11, 22, 33], [55,66,77]])
b = array([[11, 22, 33, 44], [55, 66, 77, 88]])
L = list()
L.append(a)
L.append(b)
print L
print L[0]

[array([[11, 22, 33],
       [55, 66, 77]]), array([[11, 22, 33, 44],
       [55, 66, 77, 88]])]
[[11 22 33]
 [55 66 77]]
